### ISSUE TITLE
'Uknown word' error causes build to hang

### ISSUE THREAD

**Issue by rhys-vdw** [NMFR/optimize-css-assets-webpack-plugin#14] opened 2017-08-10 06:43 UTC
Not sure of the exact issue causing this error yet. Either way it looks like an error that should be caught by this plugin so that it may cancel the build with an error:

Full stack trace below:
```
/Users/rhys/Projects/usability-hub/usability_hub/node_modules/.bin/webpack --config /Users/rhys/Projects/usability-hub/usability_hub/config/webpack.config.js --bail
clean-webpack-plugin: /Users/rhys/Projects/usability-hub/usability_hub/public/webpack_assets has been removed.
Error processing file: print-83f4ad77948c21b55de0.css
CssSyntaxError: <css input>:1:10: Unknown word
    at Input.error (/Users/rhys/Projects/usability-hub/usability_hub/node_modules/postcss/lib/input.js:113:22)
    at Parser.unknownWord (/Users/rhys/Projects/usability-hub/usability_hub/node_modules/postcss/lib/parser.js:468:26)
    at Parser.other (/Users/rhys/Projects/usability-hub/usability_hub/node_modules/postcss/lib/parser.js:174:14)
    at Parser.loop (/Users/rhys/Projects/usability-hub/usability_hub/node_modules/postcss/lib/parser.js:81:26)
    at parse (/Users/rhys/Projects/usability-hub/usability_hub/node_modules/postcss/lib/parse.js:26:16)
    at new LazyResult (/Users/rhys/Projects/usability-hub/usability_hub/node_modules/postcss/lib/lazy-result.js:70:24)
    at Processor.process (/Users/rhys/Projects/usability-hub/usability_hub/node_modules/postcss/lib/processor.js:117:12)
    at Function.cssnano.process (/Users/rhys/Projects/usability-hub/usability_hub/node_modules/cssnano/dist/index.js:306:55)
    at OptimizeCssAssetsPlugin.processCss (/Users/rhys/Projects/usability-hub/usability_hub/node_modules/optimize-css-assets-webpack-plugin/index.js:39:19)
    at Object.processor (/Users/rhys/Projects/usability-hub/usability_hub/node_modules/optimize-css-assets-webpack-plugin/index.js:28:23)
    at /Users/rhys/Projects/usability-hub/usability_hub/node_modules/last-call-webpack-plugin/index.js:117:8
    at arrayEach (/Users/rhys/Projects/usability-hub/usability_hub/node_modules/last-call-webpack-plugin/node_modules/lodash/_arrayEach.js:15:9)
    at forEach (/Users/rhys/Projects/usability-hub/usability_hub/node_modules/last-call-webpack-plugin/node_modules/lodash/forEach.js:38:10)
    at LastCallWebpackPlugin.process (/Users/rhys/Projects/usability-hub/usability_hub/node_modules/last-call-webpack-plugin/index.js:114:3)
    at Compilation.<anonymous> (/Users/rhys/Projects/usability-hub/usability_hub/node_modules/last-call-webpack-plugin/index.js:150:12)
    at Compilation.applyPluginsAsyncSeries (/Users/rhys/Projects/usability-hub/usability_hub/node_modules/tapable/lib/Tapable.js:206:13)
    at self.applyPluginsAsync.err (/Users/rhys/Projects/usability-hub/usability_hub/node_modules/webpack/lib/Compilation.js:645:11)
    at next (/Users/rhys/Projects/usability-hub/usability_hub/node_modules/tapable/lib/Tapable.js:202:11)
    at LastCallWebpackPlugin.process (/Users/rhys/Projects/usability-hub/usability_hub/node_modules/last-call-webpack-plugin/index.js:106:12)
    at Compilation.<anonymous> (/Users/rhys/Projects/usability-hub/usability_hub/node_modules/last-call-webpack-plugin/index.js:147:12)
    at Compilation.applyPluginsAsyncSeries (/Users/rhys/Projects/usability-hub/usability_hub/node_modules/tapable/lib/Tapable.js:206:13)
    at self.applyPluginsAsync.err (/Users/rhys/Projects/usability-hub/usability_hub/node_modules/webpack/lib/Compilation.js:640:10)
    at next (/Users/rhys/Projects/usability-hub/usability_hub/node_modules/tapable/lib/Tapable.js:202:11)
    at Compilation.<anonymous> (/Users/rhys/Projects/usability-hub/usability_hub/node_modules/extract-text-webpack-plugin/dist/index.js:272:11)
    at Compilation.applyPluginsAsyncSeries (/Users/rhys/Projects/usability-hub/usability_hub/node_modules/tapable/lib/Tapable.js:206:13)
    at sealPart2 (/Users/rhys/Projects/usability-hub/usability_hub/node_modules/webpack/lib/Compilation.js:636:9)
    at next (/Users/rhys/Projects/usability-hub/usability_hub/node_modules/tapable/lib/Tapable.js:202:11)
    at /Users/rhys/Projects/usability-hub/usability_hub/node_modules/extract-text-webpack-plugin/dist/index.js:241:13
    at /Users/rhys/Projects/usability-hub/usability_hub/node_modules/extract-text-webpack-plugin/node_modules/async/dist/async.js:421:16
    at iteratorCallback (/Users/rhys/Projects/usability-hub/usability_hub/node_modules/extract-text-webpack-plugin/node_modules/async/dist/async.js:998:13)
```

**Comment by NMFR** [comment] 2017-08-10 23:42
Can you provide a way to replicate please?

**Comment by rhys-vdw** [comment] 2017-08-11 01:04
Sorry we've got an obscenely large webpack config, so I wont be able to easily create a minimal working case any time soon. I thought maybe this stack trace would suggest an obvious place that the error is not being handled, but looking through the source and that of `last-call-webpack-plugin` it actually looks properly handled.

We're currently making some changes to our config, and we'll be trying this module again. If I hit the same issue I'll report back with as much info as possible.

**Comment by NMFR** [comment] 2017-08-18 22:35
I don't think the issue is on this plugin.
Just tested a CSS that throws the "Unknown word" error and it stops the build.

I am closing the issue.

If you have any more info about this please share and i will reopen.

PS: check if you didn't forget to resolve / re throw some error in a promise.

**Closed by NMFR** 2017-08-18 22:35 UTC

**Comment by rhys-vdw** [comment] 2017-08-19 06:41
Hey @NMFR, sorry I didn't get back to you. Task ended up getting handled by another team member who didn't run into the issue. I probably misconfigured something. Thanks for your time on this issue and the plugin.

**Comment by JASONPANGGO** [comment] 2022-02-21 03:43
I hava the same issue
```js
config.plugins.push(
            new OptimizeCssAssetsPlugin({
                assetNameRegExp: /\.css$/g,
                cssProcessorOptions: {
                    discardComments: {
                        removeAll: true
                    },
                    autoprefixer: false,
                    zindex: false
                },
                canPrint: true
            })
        )
```

once I remove this plugin, it can build successfully
