### ISSUE TITLE
opacity percentage changed to 1%

### ISSUE THREAD

**Issue by santiagoarizti** [NMFR/optimize-css-assets-webpack-plugin#118] opened 2020-01-16 15:16 UTC
According to MDN opacity can be expressed in percentage or in a 0-1 number.

This plugin (optimize-css-assets-webpack-plugin@^5.0.3) will work fine with opacity written in a 0-1 number, but if you express opacity in percentage terms, it will always change it to 1%

I created a public repository where you can easily reproduce the issue by running `npx webpack` and observing the output.
https://bitbucket.org/santiagoarizti/webpack-css-assets-opacity/src/3f6df7980fb4e24eefc18e752e54e587e7c98d2f/

In the readme of that same repo is a more detailed explanation of how to reproduce the issue.

**Comment by joshjordan** [comment] 2020-01-21 17:36
Do we know what version this issue began in?

**Comment by santiagoarizti** [comment] 2020-01-25 09:13
Sorry. I just know that it happens in the version I mentioned. Easily reproducable. You might be able to test eariler releases and find out

**Comment by genemecija** [comment] 2020-02-21 19:33
I think the root of the issue was a conversion error for opacity percentages in [cssnano](https://github.com/cssnano/cssnano). I submitted a [pull request](https://github.com/cssnano/cssnano/pull/881) to resolve and it was merged today.

I'm not sure what needs to be done to propagate those changes here.

**Comment by santiagoarizti** [comment] 2020-02-27 21:20
I closed the issue, but I don't know the guidelines about that, maybe I should've waited until someone verified it and shared a fix version?

**Closed** 2020-02-27 21:19 UTC

**Comment by derekparsons718** [comment] 2020-07-17 16:41
This seems to still be an issue. I am currently encountering this problem. Perhaps the issue should be reopened until the fix is confirmed.

**Comment by klesun** [comment] 2020-08-13 19:17
Happens in our project with `Vue v2.6.11`

Here is the SO thread:

https://stackoverflow.com/questions/59470947/vue-cli-build-production-change-opacity-in-css

Also relevant: https://github.com/facebook/create-react-app/issues/7980

**Comment by RyanChristian4427** [comment] 2020-09-06 15:33
@NMFR 

Sorry to ping but this issue really needs to be reopened. No idea why it was closed without resolution to begin with.

**Comment by joshjordan** [comment] 2020-09-06 15:42
@RyanChristian4427 a resolution was merged in cssnano a few weeks ago. The bug is not in this  library. What outcome are you looking for?

**Comment by RyanChristian4427** [comment] 2020-09-06 15:45
I get that, but as this library uses `cssnano`, and it has only distributed that resolution via the nightly version, all users of this library downstream don't have any access to that resolution.

**Comment by joshjordan** [comment] 2020-09-06 15:48
I’ll ask again: what outcome are you looking for?

**Comment by RyanChristian4427** [comment] 2020-09-06 15:49
To be able to use this plugin and have opacity work correctly?

**Comment by joshjordan** [comment] 2020-09-06 15:54
What outcome are you looking for from *this thread*? I don’t see any action that the maintainers of this library can take that will accomplish what you described. cssnano needs to release their next version (or you need to update to the nightly), or you need to use decimal based opacities.

**Comment by RyanChristian4427** [comment] 2020-09-06 15:59
The maintainers of this library can update `cssnano` to use the nightly version so that all users downstream can get the fix. 

I don't directly use `cssnano`. My only connection to it is via this plugin, so short of manually patching in versions to fix this plugin I'm out of luck until this library updates. Not sure what you're expecting me to do here.

**Comment by joshjordan** [comment] 2020-09-06 16:06
Well, no, wouldn’t want to encourage the maintainers here to rely on an unofficial release that may have other bugs in it — that wouldn’t be a responsible move.

You have a broken engine but you’re complaining to the tire manufacturer that your car won’t go. It is true that the tires won’t be useful until the engine is fixed, and I understand your frustration, but there’s nothing to be done here.

As far as what I expect you to do, like I said, you can either update to the nightly build yourself, or use decimal based opacity.

**Comment by RyanChristian4427** [comment] 2020-09-06 16:11
I obviously very much disagree. 

Plenty of software is released and maintained with nightly dependencies. There are ways to pin to a known good nightly build anyhow.

This is an issue that will continue to plague a few million applications until the fix is implemented here. I think that, in this case, choosing not to implement a fix for a well known issue is a bad move.

**Comment by NMFR** [comment] 2020-09-06 16:11
[optimize-css-assets-webpack-plugin](https://github.com/NMFR/optimize-css-assets-webpack-plugin) does not actually manipulate any CSS. It delegates that to the `cssProcessor`. The default `cssProcessor` is [cssnano](https://github.com/cssnano/cssnano) but the user can configure its own `cssProcessor` if he wishes.

The problem described here is a [cssnano](https://github.com/cssnano/cssnano) issue. We can't do any change (besides changing the default `cssProcessor`) to help with this.

Given the nature of CSS quirks we do get alot of `cssProcessor` [cssnano](https://github.com/cssnano/cssnano) related issues on this repo. If we don't close them we will end up with a large subset of [cssnano](https://github.com/cssnano/cssnano) replica issues that just difficult's managing the real issues of this repo. This is the reason of closing [cssnano](https://github.com/cssnano/cssnano) issues here and asking them to be opened on [cssnano](https://github.com/cssnano/cssnano) repo.

That being said, i do understand your frustration on just wanting the bug tracked and fixed across all dependencies. Do you have any suggestion on how to better track this without having a lot of issues opened on this repo where nothing can be really done to fix them (besides waiting for [cssnano](https://github.com/cssnano/cssnano) fix and release)?

**Comment by NMFR** [comment] 2020-09-06 16:19
On the "switching to the nightly version of cssnano" topic. Doing that might solve this issue for the 1% user base that are exposed to it but at the same time the other 99% run the risk of being exposed to bugs and instability that is natural from nightly versions without any clear gain. So yes we will always make an effort to stay away from depending on nightly versions.

**Comment by NMFR** [comment] 2020-09-06 16:21
Lets not forget that if you really want to use a [cssnano](https://github.com/cssnano/cssnano) nightly version you can by just including that version as a dependency and configuring [optimize-css-assets-webpack-plugin](https://github.com/NMFR/optimize-css-assets-webpack-plugin) `cssProcessor` option to use that. This is my recommendation until [cssnano](https://github.com/cssnano/cssnano) releases the fix, then we will just update the dependency on our side and release.

Sorry for the long wall of text :p

**Comment by m4heshd** [comment] 2021-02-28 15:46
The issue is still there by the way. Just ran into it.

**Comment by joshjordan** [comment] 2021-02-28 16:17
@m4heshd the issue is with cssnano. Update your version to cssnano@nightly

**Comment by m4heshd** [comment] 2021-02-28 16:44
@joshjordan Oh I see. Thanks.
