### ISSUE TITLE
why remove -webkit-box-orient property?

### ISSUE THREAD

**Issue by zLoong** [NMFR/optimize-css-assets-webpack-plugin#48] opened 2018-05-07 12:35 UTC
I use optimize-css-assets-webpack-plugin remove -webkit-box-orient: vertical；  I test not autoprefixer problem

**Comment by NMFR** [comment] 2018-05-07 21:11
Duplicate of https://github.com/NMFR/optimize-css-assets-webpack-plugin/issues/47

**Closed by NMFR** 2018-05-07 21:11 UTC
